#!/usr/bin/env python

'''
The application is a starship sales site. We are wealthy spacefarers shopping
for a new ship. We want to search for starships, sort them by cost, and filter
them by cost (if we have a starship budget we don't want to look at ships above
it.)

If there are pilots associated with the starship, we want to get more
information about them as well, because we are concerned about previous owners.

INSTALLATION:
=============

Tested with
    Python 2.7.10 on Linux

Make sure that "swapi" (https://swapi-python.readthedocs.org/en/latest/readme.html#installation) is installed
    $ pip install swapi

Install Flask, A lightweight Python web framework (http://flask.pocoo.org/)
    $ pip install Flask
'''
from flask import Flask, render_template
app = Flask(__name__)


@app.route("/")
def index():
    return render_template('index.html')

if __name__ == "__main__":
    app.debug = True
    app.run(host='0.0.0.0')
